spring:
  application:
    name: spring-ai-erudio-deepseek-ollama
  ai:
    openai:
      api-key: ${DEEP_SEEK_API_KEY}
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: "deepseek-chat"
